[phases.setup]
nixPkgs = ["python312Full", "nodejs_22"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt",
  "cd frontend && npm install --legacy-peer-deps --omit=optional && cd .."
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "/opt/venv/bin/python manage.py migrate --noinput && /opt/venv/bin/python manage.py collectstatic --noinput && /opt/venv/bin/gunicorn stargazer.wsgi --bind 0.0.0.0:$PORT --workers 3"
