[phases.setup]
nixPkgs = ["python312Full", "nodejs_22"]

[phases.install]
cmds = ["python -m ensurepip --upgrade", "python -m pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn stargazer.wsgi --bind 0.0.0.0:$PORT --workers 3"
