# Generated by Django 5.2.13 on 2026-04-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('url', models.URLField()),
                ('hdurl', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(max_length=10)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
