# Generated by Django 5.2.13 on 2026-04-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('body_type', models.CharField(max_length=100)),
                ('right_ascension', models.CharField(max_length=50)),
                ('declination', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('apod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apod.apod')),
                ('celestial_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apod.celestialbody')),
            ],
        ),
    ]
